export const COACHES = [
  {
    id: 'lyusijyun',
    chineseName: '呂西鈞',
    englishName: 'Gary Lu',
    career: [
      '1978年轉入職業球員',
      '職業冠軍26勝 (1979~1997)',
      '亞巡賽四屆總冠軍',
      '日巡賽三勝',
      '四大賽五次參賽',
      'PGA 理事長 (1996~1999)',
      '高協總教練 (2002~2016)',
      '呂西鈞高爾夫教學主持人',
    ],
    feature: [
      '球員動作慣性改造',
      '青少年輔導',
      '球場策略與執行',
      '加強短桿能力',
      '提升高爾夫樂趣',
    ],
    branch: 'shipai',
    imgUrl: '/img/GaryLu.jpg',
    imgAlt: 'Gary Lu',
    scale: 1.6,
    position: '17px -21px',
  },
  {
    id: 'tsailisiang',
    chineseName: '蔡麗香 (蔡采君)',
    englishName: 'Angel Tsai',
    career: [
      '1975年轉入職業球員',
      '生涯冠軍共14場(日本九場、台灣五場)',
      '東方高爾夫學院院長',
      '台灣女子職業高爾夫協會創辦會長第二、三任理事長',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [],
    branch: 'shipai',
    imgUrl: '/img/AngelTsai.jpg',
    imgAlt: 'Angel Tsai',
    scale: 1.8,
    position: '-1px -16px',
  },
  {
    id: 'syusing',
    chineseName: '許興',
    englishName: 'Uncle Hsu',
    career: [
      '球場管理經驗',
      '練習場管理經驗',
      '現職 水蓮練習場教練',
    ],
    feature: [
      '多年職業選手觀察經驗',
      '善於球道策略輔導',
      '女性球員教學專長',
      '兒童青少年教育輔導',
    ],
    branch: 'shipai',
    imgUrl: '/img/UncleHsu.jpg',
    imgAlt: 'Uncle Hsu',
    scale: 2.6,
    position: '1px 28px',
  },
  {
    id: 'lyurongfong',
    chineseName: '呂榮峰',
    englishName: 'Vincent Lu',
    career: [
      '2000年亞運培訓選手',
      '2000年台灣PGA專業教練',
      '專業球具組裝維修',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '學員球具選配專長',
      '擊球收桿強化訓練',
      '學員動作基礎深化',
      '球道策略執行',
      '果嶺周邊短桿技巧',
      '孩童基礎學習與進階',
    ],
    branch: 'shipai',
    imgUrl: '/img/VincentLu.jpg',
    imgAlt: 'Vincent Lu',
    scale: 2.6,
    position: '-3px 16px',
  },
  {
    id: 'jhandengkai',
    chineseName: '詹登凱',
    englishName: 'Kai Chan',
    career: [
      '2002年開始從事高爾夫教學',
      '澳洲格里菲斯大學運動管理學系高爾夫學員',
      '澳洲新英格蘭大學高爾夫管理學畢業',
      'AGTF澳洲高爾夫教練聯盟認證教練',
      '林口區興福國小專聘高爾夫教練',
      '台北美國學校高中部高爾夫校隊教練',
      '台北美國學校中學部高爾夫社團教練',
      'Titleist簽約贊助教練',
      'Positive Coaching Alliance Certified Coach',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '全英語教學',
      '兒童基本動作養成',
      '短桿選擇時機及果嶺判讀',
      '揮桿節奏控制',
      '球場策略及執行',
    ],
    branch: 'shipai',
    imgUrl: '/img/KaiChan.jpg',
    imgAlt: 'Kai Chan',
    scale: 2.1,
    position: '-4px -14px',
  },
  {
    id: 'chenweichyuan',
    chineseName: '陳韋全',
    englishName: 'Tiger Chen',
    career: [
      '文化大學體育系',
      '台灣PGA專業教練',
      'ThreeBond參賽選手',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '注重基本動作',
      '提升擊球穩定性',
      '提升擊球力量',
      '讓學員可以有自我調整錯誤的觀念',
    ],
    branch: 'shipai',
    imgUrl: '/img/TigerChen.jpg',
    imgAlt: 'Tiger Chen',
    scale: 6.7,
    position: '2px -28px',
  },
  {
    id: 'lioujingru',
    chineseName: '劉京儒',
    englishName: 'Berry Liu',
    career: [
      '台北市立體育學院高爾夫專長',
      '中華高協教練',
      'TPI Level 2',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '客製化教學',
      '提升高爾夫能力',
      '個人化球具fitting',
      '球道攻略執行',
      '兒童基本動作養成',
    ],
    branch: 'shipai',
    imgUrl: '/img/BerryLiu.jpg',
    imgAlt: 'Berry Liu',
    scale: 5.2,
    position: '5px 10px',
  },
  {
    id: 'tsailiyun',
    chineseName: '蔡麗雲',
    englishName: 'Ivy Tsai',
    career: [
      '東華球場青少年短桿訓練教練',
      '中華高協C級裁判',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '青少年團隊引領訓練',
      '兒童青少年教學輔導',
      '女性球員專業評鑑',
      '球道攻略與選桿應用',
      '短桿技巧教學',
    ],
    branch: 'shipai',
    imgUrl: '/img/IvyTsai.jpg',
    imgAlt: 'Ivy Tsai',
    scale: 3.9,
    position: '8px 6px',
  },
  {
    id: 'linzonghan',
    chineseName: '林宗翰',
    englishName: 'Andy Lin',
    career: [
      '台北城市大學高爾夫球隊',
      '揚昇高爾夫球場培訓球員',
      '全國高爾夫球場培訓球員',
      '中華民國高爾夫協會教練',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '多年觀察國內外職業選手經驗',
      '客製化教學',
      '提升高爾夫能力',
      '兒童基礎動作教學',
      '球場策略以及果嶺邊短桿運用教學',
      '提升推桿穩定性教學',
    ],
    branch: 'shipai',
    imgUrl: '/img/AndyLin.jpg',
    imgAlt: 'Andy Lin',
    scale: 1.1,
    position: '8px 3px',
  },
  {
    id: 'gaoyuwei',
    chineseName: '高育薇',
    englishName: 'Rose Kao',
    career: [
      '國立臺灣大學畢業、師大體育系碩士',
      '美國PGCC職業高爾夫球學院',
      '中華民國高爾夫協進會認證合格教練',
      '世界認證美國教練聯盟專業教練',
      '高爾夫雜誌台灣50大名師',
      '緯來博斯高球示範教學專屬教練',
      'FOX體育台專業球評',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '初學、進階依據個人差點球齡體能球路，量身訂做系統課程',
      '配合電腦分析、輔助器材，以最科學及最自然之啟發式教學',
      '成人兒童，美式教學 Simple & Fun 簡明易懂、活用生動',
      '指導球場攻略與心理學，減輕壓力技巧、避免運動傷害、修正姿勢、減少桿數',
    ],
    branch: 'bitan',
    imgUrl: '/img/RoseKao.jpg',
    imgAlt: 'Rose Kao',
    scale: 1.3,
    position: '6px -20px',
  },
  {
    id: 'linjingen',
    chineseName: '林敬恩',
    englishName: 'Aaron Lin',
    career: [
      '淡水青少年培訓選手',
      '中華高協教練',
      '呂西鈞高爾夫教學教練',
    ],
    feature: [
      '客製化教學',
      '提升高爾夫能力',
      '增加木桿開球距離',
      '個人化球具fitting',
      '球道攻略執行',
      '短距選桿球路應用',
      '兒童高爾夫啟蒙',
    ],
    branch: 'bitan',
    imgUrl: '/img/AaronLin.jpg',
    imgAlt: 'Aaron Lin',
    scale: 1.3,
    position: '-6px -6px',
  },
]

export const CONTACT = [
  {
    id: 'shipai',
    name: '石牌店',
    address: '台北市北投區承德路七段223號',
    tele: '02-2828-7313',
    link: 'https://www.google.com/maps?q=%E5%8F%B0%E5%8C%97%E5%B8%82%E5%8C%97%E6%8A%95%E5%8D%80%E6%89%BF%E5%BE%B7%E8%B7%AF%E4%B8%83%E6%AE%B5223%E8%99%9F&uact=5&um=1&ie=UTF-8&sa=X&ved=2ahUKEwjBx5-6o9_nAhXvy4sBHc7JCkAQ_AUoAXoECA0QAw',
  },
  {
    id: 'bitan',
    name: '碧潭店',
    address: '新北市新店區溪洲路121號',
    tele: '02-2212-6041',
    link: 'https://www.google.com/maps/place/231%E6%96%B0%E5%8C%97%E5%B8%82%E6%96%B0%E5%BA%97%E5%8D%80%E6%BA%AA%E6%B4%B2%E8%B7%AF121%E8%99%9F/@24.9632735,121.5287659,17z/data=!3m1!4b1!4m5!3m4!1s0x346802242601f33d:0xf263470240cae246!8m2!3d24.9632735!4d121.5309546',
  },
]

export const TECH = [
  {
    id: '001',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F839840799493788%2F',
    info: '許多球友在推桿時，對於起桿與送桿的長度與力度經常難以拿捏。我的經驗是，4：6。',
    source: '《呂老師小撇步》001',
  },
  {
    id: '002',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864640593680475%2F',
    info: '在起伏較明顯的果嶺，尤其是下坡，我會在距離判斷後找出一個轉折點，然後用減少敲擊的動作送出。',
    source: '《呂老師小撇步》002',
  },
  {
    id: '003',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864642277013640%2F',
    info: '果嶺的上坡地形，通常我會設定在過洞後的一個目標，再以足夠的送桿來達到過洞的推球概念。',
    source: '《呂老師小撇步》003',
  },
  {
    id: '004',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864654363679098%2F',
    info: '在右往左曲的長推桿，我會在弧度最大的途中設一個轉折點，然後起桿時順著地形略為往內起桿送出。',
    source: '《呂老師小撇步》004',
  },
  {
    id: '005',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864659817011886%2F',
    info: '在多變的傾斜果嶺推桿不但要掌控距離還需觀察流向，特別左至右的推球，我會設定一個接近洞口點，桿面左延伸後會經由轉折點流轉至目標。',
    source: '《呂老師小撇步》005',
  },
  {
    id: '006',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864920426985825%2F',
    info: '短切球能處理的好，可說能畫龍點睛，尤其在高爾夫球的表現上，選落點、選桿非常重要，先掌握一項技能，以P桿為例，落一半滾動一半。',
    source: '《呂老師小撇步》006',
  },
  {
    id: '007',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864926056985262%2F',
    info: '果嶺邊的切球，有多種不同距離與選桿，52度 切桿帶有稍微滾動的球路是不錯的選擇。',
    source: '《呂老師小撇步》007',
  },
  {
    id: '008',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864930670318134%2F',
    info: `在落地後沒有太多滾動空間的旗位，只能使用最大開放角度(58或60)的切桿。\n★上桿時適度的曲起手腕，下擊動作力量運用在第一段。`,
    source: '《呂老師小撇步》008',
  },
  {
    id: '009',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864939010317300%2F',
    info: `沙坑球是多數球友的夢魘，除了需要一支得宜的切桿。\n★重點在起落的過程，保持一致的揮桿速度並防止翻轉桿面。`,
    source: '《呂老師小撇步》009',
  },
  {
    id: '010',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864945516983316%2F',
    info: `常見的低球位，最容易在擊球時往右偏。\n★因此設定方向於左側，減少身體上揚，往外起桿不翻轉桿面。`,
    source: '《呂老師小撇步》010',
  },
  {
    id: '011',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864955366982331%2F',
    info: `球道中難免有地形起伏的狀況，首要注意的是站姿的設定，左高右低的上坡球因為重心轉移不易，容易使桿面翻轉而球路偏左。\n★因此設定時重心多於右側(低方)在於起桿時略微往內。`,
    source: '《呂老師小撇步》011',
  },
  {
    id: '012',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F864969633647571%2F',
    info: `球道中有不平的球位都有它的難度，尤其右高左低的技術球。\n★先設定重心於左側(低方)再略為往外起桿，才能充分取用到桿面由上而下。`,
    source: '《呂老師小撇步》012',
  },
  {
    id: '013',
    url: 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flhcgolf%2Fvideos%2F1974642199346970%2F',
    info: `球道沙坑擊球會因為站位鬆動而影響揮桿。\n★除了稍握短桿身，少一號的揮桿幅度，盡量減少身體移動。`,
    source: '《呂老師小撇步》013',
  },
]

export const VIDEO = [
  {
    id: 1,
    name: '高爾夫基礎：握桿方式',
    url: 'https://www.youtube.com/watch?v=zFKCp_YN10Y',
  },
  {
    id: 2,
    name: '上桿左手為什麼不直？',
    url: 'https://www.youtube.com/watch?v=kWRZpU7P81g',
  },
  {
    id: 3,
    name: '下桿雙手如何直？',
    url: 'https://www.youtube.com/watch?v=Sv-OtNHuG9E',
  },
  {
    id: 4,
    name: 'Tiger Woods 2018 動作解析',
    url: 'https://www.youtube.com/watch?v=pKpAXBVImag',
  },
]

export const GALLERY = [
  {
    id: 1,
    url: '/img/gallery/photo01.jpg',
    alt: 'photo01',
  },
  {
    id: 2,
    url: '/img/gallery/photo02.jpg',
    alt: 'photo02',
  },
  {
    id: 3,
    url: '/img/gallery/photo03.jpg',
    alt: 'photo03',
  },
  {
    id: 4,
    url: '/img/gallery/photo04.jpg',
    alt: 'photo04',
  },
  {
    id: 5,
    url: '/img/gallery/photo05.jpg',
    alt: 'photo05',
  },
  {
    id: 6,
    url: '/img/gallery/photo06.jpg',
    alt: 'photo06',
  },
  {
    id: 7,
    url: '/img/gallery/photo07.jpg',
    alt: 'photo07',
  },
  {
    id: 8,
    url: '/img/gallery/photo08.jpg',
    alt: 'photo08',
  },
]